In [1]:
import pandas as pd
import numpy as np
from io import StringIO

In [2]:
import csv

In [3]:
data = []
with open("/home/gagan/open_audio_datasets/0031244-250525065834625/occurrence.txt", "r") as f:
    for line in f.readlines():
        data.append(line.strip())

In [4]:
len(data)

795539

In [13]:
df = pd.read_csv('/home/gagan/open_audio_datasets/0031244-250525065834625/occurrence.txt', 
                 sep='\t', 
                 engine='python',  # More flexible parser
                 on_bad_lines='skip',
                 quoting=csv.QUOTE_NONE)

In [53]:
df.shape

(795538, 223)

In [15]:
cols = list(df.columns)

In [16]:
cols

['gbifID',
 'accessRights',
 'bibliographicCitation',
 'language',
 'license',
 'modified',
 'publisher',
 'references',
 'rightsHolder',
 'type',
 'institutionID',
 'collectionID',
 'datasetID',
 'institutionCode',
 'collectionCode',
 'datasetName',
 'ownerInstitutionCode',
 'basisOfRecord',
 'informationWithheld',
 'dataGeneralizations',
 'dynamicProperties',
 'occurrenceID',
 'catalogNumber',
 'recordNumber',
 'recordedBy',
 'recordedByID',
 'individualCount',
 'organismQuantity',
 'organismQuantityType',
 'sex',
 'lifeStage',
 'reproductiveCondition',
 'caste',
 'behavior',
 'vitality',
 'establishmentMeans',
 'degreeOfEstablishment',
 'pathway',
 'georeferenceVerificationStatus',
 'occurrenceStatus',
 'preparations',
 'disposition',
 'associatedOccurrences',
 'associatedReferences',
 'associatedSequences',
 'associatedTaxa',
 'otherCatalogNumbers',
 'occurrenceRemarks',
 'organismID',
 'organismName',
 'organismScope',
 'associatedOrganisms',
 'previousIdentifications',
 'organismRemarks',
 'materialEntityID',
 'materialEntityRemarks',
 'verbatimLabel',
 'materialSampleID',
 'eventID',
 'parentEventID',
 'eventType',
 'fieldNumber',
 'eventDate',
 'eventTime',
 'startDayOfYear',
 'endDayOfYear',
 'year',
 'month',
 'day',
 'verbatimEventDate',
 'habitat',
 'samplingProtocol',
 'sampleSizeValue',
 'sampleSizeUnit',
 'samplingEffort',
 'fieldNotes',
 'eventRemarks',
 'locationID',
 'higherGeographyID',
 'higherGeography',
 'continent',
 'waterBody',
 'islandGroup',
 'island',
 'countryCode',
 'stateProvince',
 'county',
 'municipality',
 'locality',
 'verbatimLocality',
 'verbatimElevation',
 'verticalDatum',
 'verbatimDepth',
 'minimumDistanceAboveSurfaceInMeters',
 'maximumDistanceAboveSurfaceInMeters',
 'locationAccordingTo',
 'locationRemarks',
 'decimalLatitude',
 'decimalLongitude',
 'coordinateUncertaintyInMeters',
 'coordinatePrecision',
 'pointRadiusSpatialFit',
 'verbatimCoordinateSystem',
 'verbatimSRS',
 'footprintWKT',
 'footprintSRS',
 'footprintSpatialFit',
 'georeferencedBy',
 'georeferencedDate',
 'georeferenceProtocol',
 'georeferenceSources',
 'georeferenceRemarks',
 'geologicalContextID',
 'earliestEonOrLowestEonothem',
 'latestEonOrHighestEonothem',
 'earliestEraOrLowestErathem',
 'latestEraOrHighestErathem',
 'earliestPeriodOrLowestSystem',
 'latestPeriodOrHighestSystem',
 'earliestEpochOrLowestSeries',
 'latestEpochOrHighestSeries',
 'earliestAgeOrLowestStage',
 'latestAgeOrHighestStage',
 'lowestBiostratigraphicZone',
 'highestBiostratigraphicZone',
 'lithostratigraphicTerms',
 'group',
 'formation',
 'member',
 'bed',
 'identificationID',
 'verbatimIdentification',
 'identificationQualifier',
 'typeStatus',
 'identifiedBy',
 'identifiedByID',
 'dateIdentified',
 'identificationReferences',
 'identificationVerificationStatus',
 'identificationRemarks',
 'taxonID',
 'scientificNameID',
 'acceptedNameUsageID',
 'parentNameUsageID',
 'originalNameUsageID',
 'nameAccordingToID',
 'namePublishedInID',
 'taxonConceptID',
 'scientificName',
 'acceptedNameUsage',
 'parentNameUsage',
 'originalNameUsage',
 'nameAccordingTo',
 'namePublishedIn',
 'namePublishedInYear',
 'higherClassification',
 'kingdom',
 'phylum',
 'class',
 'order',
 'superfamily',
 'family',
 'subfamily',
 'tribe',
 'subtribe',
 'genus',
 'genericName',
 'subgenus',
 'infragenericEpithet',
 'specificEpithet',
 'infraspecificEpithet',
 'cultivarEpithet',
 'taxonRank',
 'verbatimTaxonRank',
 'vernacularName',
 'nomenclaturalCode',
 'taxonomicStatus',
 'nomenclaturalStatus',
 'taxonRemarks',
 'datasetKey',
 'publishingCountry',
 'lastInterpreted',
 'elevation',
 'elevationAccuracy',
 'depth',
 'depthAccuracy',
 'distanceFromCentroidInMeters',
 'issue',
 'mediaType',
 'hasCoordinate',
 'hasGeospatialIssues',
 'taxonKey',
 'acceptedTaxonKey',
 'kingdomKey',
 'phylumKey',
 'classKey',
 'orderKey',
 'familyKey',
 'genusKey',
 'subgenusKey',
 'speciesKey',
 'species',
 'acceptedScientificName',
 'verbatimScientificName',
 'typifiedName',
 'protocol',
 'lastParsed',
 'lastCrawled',
 'repatriated',
 'relativeOrganismQuantity',
 'projectId',
 'isSequenced',
 'gbifRegion',
 'publishedByGbifRegion',
 'level0Gid',
 'level0Name',
 'level1Gid',
 'level1Name',
 'level2Gid',
 'level2Name',
 'level3Gid',
 'level3Name',
 'iucnRedListCategory']

In [21]:
verbatim = pd.read_csv("/home/gagan/open_audio_datasets/0031244-250525065834625/verbatim.txt",
                         sep='\t', 
                     engine='python',  # More flexible parser
                     on_bad_lines='skip', nrows=10,
                     quoting=csv.QUOTE_NONE)

In [23]:
verbatim_cols = list(verbatim.columns)

In [ ]:
cols

In [6]:
multimedia = pd.read_csv("/home/gagan/open_audio_datasets/0031244-250525065834625/multimedia.txt",
                         sep='\t', 
                     engine='python',  # More flexible parser
                     on_bad_lines='skip',
                     quoting=csv.QUOTE_NONE)

In [9]:
multimedia.shape

(2386614, 15)

In [10]:
multimedia.head(3)

,gbifID,type,format,identifier,references,title,description,source,audience,created,creator,contributor,publisher,license,rightsHolder
0,2243612868,StillImage,image/png,https://xeno-canto.org/sounds/uploaded/OH38YHK...,NaN,NaN,Oscillogram of the first ten seconds of the so...,NaN,NaN,NaN,Stichting Xeno-canto voor Natuurgeluiden,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/3.0/,Stichting Xeno-canto voor Natuurgeluiden
1,2243612868,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/OH38YHK...,NaN,NaN,24 s,NaN,NaN,NaN,Bob Planqué,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/3.0/,Bob Planqué
2,2243612868,StillImage,image/png,https://xeno-canto.org/sounds/uploaded/OH38YHK...,NaN,NaN,Spectrogram of the first ten seconds of the so...,NaN,NaN,NaN,Stichting Xeno-canto voor Natuurgeluiden,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/3.0/,Stichting Xeno-canto voor Natuurgeluiden

In [11]:
audio = multimedia[multimedia["type"] == "Sound"]
audio.shape

(795537, 15)

In [19]:
audio.columns

Index(['gbifID', 'type', 'format', 'identifier', 'references', 'title',
       'description', 'source', 'audience', 'created', 'creator',
       'contributor', 'publisher', 'license', 'rightsHolder'],
      dtype='object')

In [19]:
audio.sample(10)

,gbifID,type,format,identifier,references,title,description,source,audience,created,creator,contributor,publisher,license,rightsHolder
986038,2243878091,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/RGSEIIJ...,NaN,NaN,80 s,NaN,NaN,NaN,Bram Piot,NaN,NaN,http://creativecommons.org/licenses/by-nc-nd/2.5/,Bram Piot
1866953,2243841939,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/CCUCXWC...,NaN,NaN,15 s,NaN,NaN,NaN,nick talbot,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/4.0/,nick talbot
1018826,2848587894,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/XIBLXHR...,NaN,NaN,75 s,NaN,NaN,NaN,Uku Paal,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/4.0/,Uku Paal
81750,3353664460,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/RFTXRYB...,NaN,NaN,76 s,NaN,NaN,NaN,Paul Marvin,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/4.0/,Paul Marvin
682761,2609680816,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/XMFDPAC...,NaN,NaN,56 s,NaN,NaN,NaN,Mauricio Álvarez-Rebolledo,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/4.0/,Mauricio Álvarez-Rebolledo
2195979,2243643797,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/OOECIWC...,NaN,NaN,27 s,NaN,NaN,NaN,Peter Boesman,NaN,NaN,http://creativecommons.org/licenses/by-nc-nd/4.0/,Peter Boesman
1882650,3994959582,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/CCOLFGG...,NaN,NaN,22 s,NaN,NaN,NaN,Allistair Fresse,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/4.0/,Allistair Fresse
1412009,3051588583,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/OXOBWLV...,NaN,NaN,6 s,NaN,NaN,NaN,Samuel Levy,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/4.0/,Samuel Levy
1403153,2848602777,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/KDNLNVN...,NaN,NaN,8 s,NaN,NaN,NaN,Martin Sutherland,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/4.0/,Martin Sutherland
1393872,3353664508,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/PAEQEUH...,NaN,NaN,51 s,NaN,NaN,NaN,Irish Wildlife Sounds,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/4.0/,Irish Wildlife Sounds

In [40]:
audio.identifier.sample(3).to_dict()

{222036: 'https://xeno-canto.org/sounds/uploaded/KZYUWIRZVH/XC828149-WARBLER_Tennessee-Rock-Bridge-Tr-300m-DBNF-051323-0959.wav',
 2067714: 'https://xeno-canto.org/sounds/uploaded/DREKKBLICT/XC340101-Cettis%20Meijendel%2025102016%20nr1.mp3',
 499495: 'https://xeno-canto.org/sounds/uploaded/BTOFEKXFGW/XC198659-T09.mp3'}

## Duplicates ?

In [38]:
audio = audio.drop_duplicates(subset=["gbifID", "identifier"])
audio.shape

(795537, 15)

# Xeno-canto info from foundation-model-data

In [3]:
xc = pd.read_csv("gs://foundation-model-data/xeno-canto/xeno_canto_2025_v1.csv")

In [4]:
xc.shape

(590009, 22)

In [5]:
xc.columns

Index(['dataset', 'location', 'caption', 'caption2', 'species',
       'scientific_name', 'description', 'url', 'path', 'associatedMedia',
       'behavior', 'sex', 'lifeStage', 'rightsHolder', 'license', 'fieldNotes',
       'Associated Taxa', 'longitudeDecimal', 'latitudeDecimal', 'eventDate',
       'eventTime', 'multimedia_license'],
      dtype='object')

In [13]:
xc.head(3)

,dataset,location,caption,caption2,species,scientific_name,description,url,path,associatedMedia,...,lifeStage,rightsHolder,license,fieldNotes,Associated Taxa,longitudeDecimal,latitudeDecimal,eventDate,eventTime,multimedia_license
0,xeno-canto,audio/xeno-canto/Sickle-bearing Bush-cricket/X...,"Calling song, and female song of a sickle-bear...","Calling song, and female song of a sickle-bear...",Sickle-bearing Bush-cricket,Phaneroptera falcata,original filename: P_falcata_2019_017a M1 W7+ ...,https://xeno-canto.org/sounds/uploaded/KWCPMUX...,audios/xeno-canto/Sickle-bearing Bush-cricket/...,https://xeno-canto.org/sounds/uploaded/KWCPMUX...,...,adult,NaN,NaN,original filename: P_falcata_2019_017a M1 W7+ ...,NaN,11.6166,52.3170,2019-07-26,19:30,CC BY-SA 4.0
1,xeno-canto,audio/xeno-canto/Identity unknown/XC909360-Mix...,Calling song of a identity unknown sex: male. ...,Calling song of a identity unknown sex: male. ...,Identity unknown,Mystery mystery,"This is an undescribed species, potentially wi...",https://xeno-canto.org/sounds/uploaded/PLNKGHY...,audios/xeno-canto/Identity unknown/XC909360-Mi...,https://xeno-canto.org/sounds/uploaded/PLNKGHY...,...,adult,NaN,NaN,"This is an undescribed species, potentially wi...",NaN,20.4866,40.0640,2021-08-26,17:02,CC BY-NC-SA 4.0
2,xeno-canto,audio/xeno-canto/Identity unknown/XC909730-Cic...,Uncertain of a identity unknown,Uncertain of a identity unknown,Identity unknown,Mystery mystery,Cicada; animal seen:no; playback used:no,https://xeno-canto.org/sounds/uploaded/UWHBFUY...,audios/xeno-canto/Identity unknown/XC909730-Ci...,https://xeno-canto.org/sounds/uploaded/UWHBFUY...,...,NaN,NaN,NaN,Cicada; animal seen:no; playback used:no,NaN,-86.2685,32.0373,2019-09-22,14:10,CC BY-NC-SA 4.0

In [ ]:
xc.sample(5).to_dict()

In [15]:
sorted(xc.location.tolist()) == sorted(xc.path.tolist())

False

## Check which of the xc cols in our dataset (xeno_canto_2025_v1.csv) are present in new dump

In [18]:
print([c for c in cols if c in list(xc.columns)])

['license', 'rightsHolder', 'sex', 'lifeStage', 'behavior', 'eventDate', 'eventTime', 'fieldNotes', 'species']

In [20]:
print([c for c in list(audio.columns) if c in list(xc.columns)])

['description', 'license', 'rightsHolder']

In [24]:
print([c for c in list(verbatim_cols) if c in list(xc.columns)])

['license', 'rightsHolder', 'sex', 'lifeStage', 'behavior', 'associatedMedia', 'eventDate', 'eventTime', 'fieldNotes']

In [33]:
[c for c in verbatim_cols if "loca" in c]

['locationID', 'locality', 'locationAccordingTo', 'locationRemarks']

In [27]:
[c for c in verbatim_cols if "longitude" in c]

[]

In [55]:
[c for c in cols if "loca" in c]

['locationID', 'locality', 'locationAccordingTo', 'locationRemarks']

# What needs to be downloaded?

In [16]:
already_there = audio["identifier"].isin(xc["url"])
already_there

1           True
4          False
6           True
9           True
14          True
           ...
2386601     True
2386603     True
2386606     True
2386608     True
2386613     True
Name: identifier, Length: 795537, dtype: bool

In [17]:
to_download = audio["identifier"].iloc[np.where(already_there == False)[0]]
to_download.shape

(223942,)

In [18]:
to_download.to_csv("./xc_to_download.csv", index=False)

# Create the new metadata csv for the recent dump

In [46]:
import os
from urllib.parse import urlparse
import numpy as np
from pathlib import Path

In [36]:
downloaded_xc = os.listdir("/home/gagan/esp_projects/esp-data/scripts/xeno_canto_audio/")
len(downloaded_xc)

225190

In [65]:
audio = audio.reset_index(drop=True)
audio.head(5)

,level_0,index,gbifID,type,format,identifier,references,title,description,source,audience,created,creator,contributor,publisher,license,rightsHolder
0,0,1,2243612868,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/OH38YHK...,NaN,NaN,24 s,NaN,NaN,NaN,Bob Planqué,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/3.0/,Bob Planqué
1,1,4,4062431942,Sound,audio/vnd.wave,https://xeno-canto.org/sounds/uploaded/BTOFEKX...,NaN,NaN,33 s,NaN,NaN,NaN,david m,NaN,NaN,http://creativecommons.org/licenses/by-nc-nd/4.0/,david m
2,2,6,2243864926,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/OH38YHK...,NaN,NaN,20 s,NaN,NaN,NaN,Bob Planqué,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/3.0/,Bob Planqué
3,3,9,4062431947,Sound,audio/vnd.wave,https://xeno-canto.org/sounds/uploaded/TFOGOEN...,NaN,NaN,17 s,NaN,NaN,NaN,Stephan Risch,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/4.0/,Stephan Risch
4,4,14,2243888155,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/OH38YHK...,NaN,NaN,18 s,NaN,NaN,NaN,Bob Planqué,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/3.0/,Bob Planqué

In [66]:
audio = audio.drop(["level_0", "index"], axis=1)
audio.shape

(795537, 15)

In [67]:
audio.head(3)

,gbifID,type,format,identifier,references,title,description,source,audience,created,creator,contributor,publisher,license,rightsHolder
0,2243612868,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/OH38YHK...,NaN,NaN,24 s,NaN,NaN,NaN,Bob Planqué,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/3.0/,Bob Planqué
1,4062431942,Sound,audio/vnd.wave,https://xeno-canto.org/sounds/uploaded/BTOFEKX...,NaN,NaN,33 s,NaN,NaN,NaN,david m,NaN,NaN,http://creativecommons.org/licenses/by-nc-nd/4.0/,david m
2,2243864926,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/OH38YHK...,NaN,NaN,20 s,NaN,NaN,NaN,Bob Planqué,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/3.0/,Bob Planqué

In [68]:
total_audio_filenames = {os.path.basename(urlparse(row["identifier"]).path): i for i, row in audio.iterrows()}

In [69]:
total_audio_filenames_stems = {Path(f).stem: i for f,i in total_audio_filenames.items()}

In [70]:
list(total_audio_filenames_stems.keys())[:5]

['citrine_warbler_song',
 'XC784228-MIXPRE-400',
 'CinnamonthrWoodcreeper-los2-82',
 'XC784264-230211_1294-1104-Bengalenpirol.-THL%2C-Petchaburi%2C-Kaeng-Krachan%2C-Baan-Maka-Nature-Resort.-Stephan-Risch',
 'GoldencrownedSpadebill-los3-87']

In [58]:
from tqdm.notebook import tqdm
import pdb

In [83]:
new_xc_data = []
not_found = {}

for i, fname in tqdm(enumerate(downloaded_xc), total=len(downloaded_xc)):

    record = {}
    # look for the same file in audio
    if fname not in total_audio_filenames:
        # check again but this time with just the stem
        fstem = Path(fname).stem
        if fstem not in total_audio_filenames_stems:
            not_found[fname] = i
            continue
        else:
            # get the gbifID
            audio_rec = audio.iloc[total_audio_filenames_stems[fstem]]
            gbifID = audio_rec["gbifID"]
            record.update(audio_rec.loc[['gbifID','description', 'license', 'rightsHolder']].to_dict())
    else:
        # get the gbifID
        audio_rec = audio.iloc[total_audio_filenames[fname]]
        gbifID = audio_rec["gbifID"]
        record.update(audio_rec[['gbifID','description', 'license', 'rightsHolder']].to_dict())

    occurence_record = df[df["gbifID"] == gbifID]
    if len(occurence_record) > 1:
        raise Exception("What the fuck")
    occurence_record = occurence_record[['license', 'rightsHolder', 'sex', 'lifeStage', 'behavior',
                                         'kingdom', 'phylum', 'class', 'order', 'family', 'genus',
                                         'eventDate', 'eventTime', 'fieldNotes', 'species', 'locality']].iloc[0].to_dict()

    record.update(occurence_record)
    record["file_name"] = fname
    record["url"] = audio_rec["identifier"]
    new_xc_data.append(record)

  0%|          | 0/225190 [00:00<?, ?it/s]

In [74]:
len(new_xc_data)

223403

In [84]:
new_xc_data = pd.DataFrame(new_xc_data)

In [85]:
new_xc_data.head(5)

,gbifID,description,license,rightsHolder,sex,lifeStage,behavior,kingdom,phylum,class,order,family,genus,eventDate,eventTime,fieldNotes,species,locality,file_name,url
0,5151720443,161 s,CC_BY_NC_4_0,Esperanza Poveda,Male,Adult,song,Animalia,Chordata,Aves,Passeriformes,Phylloscopidae,Phylloscopus,2018-06-22,NaN,grabado en bosque mixto bastante denso de pino...,Phylloscopus bonelli,"Sierra de Francia y Quilamas (near El Maíllo),...",XC961307-phylloscopus-bonelli-2-camino-del-ma%...,https://xeno-canto.org/sounds/uploaded/PRVFBYI...
1,2243556895,12 s,CC_BY_NC_4_0,Jelmer Poelstra,NaN,NaN,call,Animalia,Chordata,Aves,Passeriformes,Emberizidae,Emberiza,2012-08-30,07:20,Four tick-calls given while perched. Rather sh...,Emberiza citrinella,"Björn, Uppland",120830_01_Yellowhammer_Bjorn_N5.mp3,https://xeno-canto.org/sounds/uploaded/RKAYEOO...
2,4940939543,5 s,CC_BY_NC_4_0,Tiiu Tali,NaN,NaN,nocturnal flight call,Animalia,Chordata,Aves,Pelecaniformes,Ardeidae,Botaurus,2024-09-03,00:30,animal seen:no; playback used:no,Botaurus stellaris,"Tammsaare, Tartu City, Tartu maakond",XC931577-BOTSTE_NFC_240903_kl0031_Tammsaare_TT...,https://xeno-canto.org/sounds/uploaded/VTBSPKD...
3,3886143518,10 s,CC_BY_NC_4_0,Frank Lambert,NaN,NaN,flight call,Animalia,Chordata,Aves,Pelecaniformes,Ardeidae,Egretta,2021-12-07,07:54,animal seen:yes; playback used:no,Egretta gularis,"Nahud, Al Birk mangroves, Aseer Province",XC741260-Western%20Reef%20Egret-FL%20flight%20...,https://xeno-canto.org/sounds/uploaded/YTUXOCT...
4,4538106500,174 s,CC_BY_NC_4_0,Marc Anderson,Indeterminate,NaN,song,Animalia,Chordata,Aves,Galliformes,Numididae,Numida,2023-09-08,07:00,animal seen:no; playback used:no,Numida meleagris,Northern Tuli Game Reserve,XC878083-Guineafowl_Helmeted2_M6EW-1015_Tuli_M...,https://xeno-canto.org/sounds/uploaded/EHGWCIG...

In [86]:
new_xc_data.to_csv("gs://xeno-canto/dump_2025/xeno_canto_metadata.csv", index=False)

In [ ]:
new_xc_data["species"]

In [108]:
new_xc_cols = set(list(new_xc_data.columns))
old_xc_cols = set(list(xc.columns))

In [109]:
old_xc_cols.difference(new_xc_cols)

{'Associated Taxa',
 'associatedMedia',
 'caption',
 'caption2',
 'dataset',
 'latitudeDecimal',
 'location',
 'longitudeDecimal',
 'multimedia_license',
 'path',
 'scientific_name'}

# Add location parameters 'latitudeDecimal' and 'longitudeDecimal' using Darwin core archive

In [91]:
darwin = pd.read_csv("/home/gagan/open_audio_datasets/0031244-250525065834625/wildlife-sounds-birds-20250703.dwca/Occurrence.txt")

/tmp/ipykernel_13544/3370568080.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  darwin = pd.read_csv("/home/gagan/open_audio_datasets/0031244-250525065834625/wildlife-sounds-birds-20250703.dwca/Occurrence.txt")

In [92]:
darwin.shape

(795538, 37)

In [94]:
darwin.columns

Index(['id', 'occurrenceID', 'catalogNumber', 'basisOfRecord',
       'collectionCode', 'dynamicProperties', 'otherCatalogNumbers', 'genus',
       'specificEpithet', 'infraspecificEpithet', 'scientificName',
       'taxonRank', 'kingdom', 'family', 'higherClassification',
       'nomenclaturalCode', 'identificationRemarks', 'vernacularName',
       'longitudeDecimal', 'latitudeDecimal', 'geodeticDatum', 'country',
       'locality', 'verbatimElevation', 'recordedBy', 'eventDate', 'eventTime',
       'verbatimEventDate', 'fieldNotes', 'behavior', 'sex', 'lifeStage',
       'preparations', 'references', 'Associated Taxa', 'rightsHolder',
       'license'],
      dtype='object')

In [93]:
darwin.head(3)

,id,occurrenceID,catalogNumber,basisOfRecord,collectionCode,dynamicProperties,otherCatalogNumbers,genus,specificEpithet,infraspecificEpithet,...,verbatimEventDate,fieldNotes,behavior,sex,lifeStage,preparations,references,Associated Taxa,rightsHolder,license
0,9@XC,https://data.biodiversitydata.nl/xeno-canto/ob...,XC9,HumanObservation,Wildlife sounds - Birds,NaN,NaN,Synallaxis,azarae,media,...,12-08-2002,two birds trip:http://www.cs.bris.ac.uk/home/p...,song,NaN,NaN,field recording,https://data.biodiversitydata.nl/xeno-canto/ob...,NaN,Bob Planqué,CC BY-NC
1,99@XC,https://data.biodiversitydata.nl/xeno-canto/ob...,XC99,HumanObservation,Wildlife sounds - Birds,NaN,NaN,Turdus,hauxwelli,NaN,...,01-10-2003,trip:http://www.cs.bris.ac.uk/home/planque/Peru/,song,NaN,NaN,field recording,https://data.biodiversitydata.nl/xeno-canto/ob...,NaN,Bob Planqué,CC BY-NC
2,9999@XC,https://data.biodiversitydata.nl/xeno-canto/ob...,XC9999,HumanObservation,Wildlife sounds - Birds,NaN,NaN,Myrmothera,campanisona,signata,...,04-03-1998,NaN,song,NaN,NaN,field recording,https://data.biodiversitydata.nl/xeno-canto/ob...,has background sounds: Selenidera reinwardtii,Allen T. Chartier,CC BY-NC

In [96]:
darwin_multimedia = pd.read_csv("/home/gagan/open_audio_datasets/0031244-250525065834625/wildlife-sounds-birds-20250703.dwca/Multimedia.txt")
darwin_multimedia.columns

Index(['CoreId', 'associatedObservationReference', 'Identifier', 'type',
       'Rating', 'rightsHolder', 'creator', 'accessURI', 'format',
       'variantLiteral', 'description', 'caption', 'resourceCreationTechnique',
       'captureDevice', 'physicalSetting', 'license'],
      dtype='object')

In [98]:
darwin.shape

(795538, 37)

In [121]:
darwin_multimedia.head(3)

,CoreId,associatedObservationReference,Identifier,type,Rating,rightsHolder,creator,accessURI,format,variantLiteral,description,caption,resourceCreationTechnique,captureDevice,physicalSetting,license
0,9@XC,https://data.biodiversitydata.nl/xeno-canto/ob...,https://xeno-canto.org/sounds/uploaded/OH38YHK...,StillImage,NaN,Stichting Xeno-canto voor Natuurgeluiden,Stichting Xeno-canto voor Natuurgeluiden,https://xeno-canto.org/sounds/uploaded/OH38YHK...,image/png,ac:MediumQuality,NaN,Oscillogram of the first ten seconds of the so...,NaN,NaN,NaN,CC BY-NC-SA 3.0
1,9@XC,https://data.biodiversitydata.nl/xeno-canto/ob...,https://xeno-canto.org/sounds/uploaded/OH38YHK...,StillImage,NaN,Stichting Xeno-canto voor Natuurgeluiden,Stichting Xeno-canto voor Natuurgeluiden,https://xeno-canto.org/sounds/uploaded/OH38YHK...,image/png,ac:MediumQuality,NaN,Spectrogram of the first ten seconds of the so...,NaN,NaN,NaN,CC BY-NC-SA 3.0
2,9@XC,https://data.biodiversitydata.nl/xeno-canto/ob...,https://xeno-canto.org/sounds/uploaded/OH38YHK...,Sound,5.0,Bob Planqué,Bob Planqué,https://xeno-canto.org/sounds/uploaded/OH38YHK...,audio/mp3,ac:BestQuality,17 s,NaN,automatic recording: no; bitrate: 64000 bps; b...,NaN,Natural,CC BY-NC-SA 3.0

In [124]:
darwin_multi_sub = darwin_multimedia[darwin_multimedia["type"] == "Sound"]
darwin_multi_sub.shape

(795503, 16)

In [126]:
(darwin_multi_sub["Identifier"] == darwin_multi_sub["accessURI"]).sum()

np.int64(795503)

In [127]:
urllist = new_xc_data["url"].tolist()

In [128]:
len(urllist)

223403

#### Find those rows of darwin multimedia where the URL matches the one's we've already downloaded in new_xc_data

In [131]:
matching_inds = np.where(darwin_multi_sub["Identifier"].isin(urllist) == True)[0]
matching_inds.shape

(223400,)

#### Issue: do the rows of darwin_multi_sub match rows of darwin?

In [132]:
coreid = darwin_multi_sub["CoreId"].iloc[matching_inds[0]]
darwin[darwin['id'] == coreid]

,id,occurrenceID,catalogNumber,basisOfRecord,collectionCode,dynamicProperties,otherCatalogNumbers,genus,specificEpithet,infraspecificEpithet,...,verbatimEventDate,fieldNotes,behavior,sex,lifeStage,preparations,references,Associated Taxa,rightsHolder,license
3,99999@XC,https://data.biodiversitydata.nl/xeno-canto/ob...,XC99999,HumanObservation,Wildlife sounds - Birds,NaN,NaN,Glaucidium,peruanum,NaN,...,2011-7-5,NaN,song,NaN,NaN,field recording,https://data.biodiversitydata.nl/xeno-canto/ob...,has background sounds: Crypturellus soui,Leonardo Ordóñez-Delgado,CC BY-NC

In [142]:
latdec = [pd.NA for _ in range(len(new_xc_data))]
longdec = [pd.NA for _ in range(len(new_xc_data))]
vernacularname = [pd.NA for _ in range(len(new_xc_data))]

In [143]:


for i in tqdm(range(len(matching_inds))):

    coreid = darwin_multi_sub["CoreId"].iloc[matching_inds[i]]
    dsub = darwin[darwin['id'] == coreid]
    idx = urllist.index(darwin_multi_sub["Identifier"].iloc[matching_inds[i]])
    
    assert len(dsub) == 1, "too many matches"
    assert dsub["rightsHolder"].iloc[0] == new_xc_data["rightsHolder"].iloc[idx], "Rights holder doesnt match"
    
    latdec[idx] = dsub["latitudeDecimal"].iloc[0]
    longdec[idx] = dsub["longitudeDecimal"].iloc[0]
    vernacularname[idx] = dsub["vernacularName"].iloc[0]

  0%|          | 0/223400 [00:00<?, ?it/s]

In [144]:
sum([isinstance(x, pd._libs.missing.NAType) for x in latdec])

34

In [147]:
new_xc_data_v2 = new_xc_data.assign(**{"latitudeDecimal": latdec, "longitudeDecimal": longdec, "vernacularName": vernacularname},)

In [148]:
new_xc_data_v2.head(10)

,gbifID,description,license,rightsHolder,sex,lifeStage,behavior,kingdom,phylum,class,...,eventDate,eventTime,fieldNotes,species,locality,file_name,url,latitudeDecimal,longitudeDecimal,vernacularName
0,5151720443,161 s,CC_BY_NC_4_0,Esperanza Poveda,Male,Adult,song,Animalia,Chordata,Aves,...,2018-06-22,NaN,grabado en bosque mixto bastante denso de pino...,Phylloscopus bonelli,"Sierra de Francia y Quilamas (near El Maíllo),...",XC961307-phylloscopus-bonelli-2-camino-del-ma%...,https://xeno-canto.org/sounds/uploaded/PRVFBYI...,40.5347,-6.1584,Western Bonelli's Warbler
1,2243556895,12 s,CC_BY_NC_4_0,Jelmer Poelstra,NaN,NaN,call,Animalia,Chordata,Aves,...,2012-08-30,07:20,Four tick-calls given while perched. Rather sh...,Emberiza citrinella,"Björn, Uppland",120830_01_Yellowhammer_Bjorn_N5.mp3,https://xeno-canto.org/sounds/uploaded/RKAYEOO...,60.637,17.98,Yellowhammer
2,4940939543,5 s,CC_BY_NC_4_0,Tiiu Tali,NaN,NaN,nocturnal flight call,Animalia,Chordata,Aves,...,2024-09-03,00:30,animal seen:no; playback used:no,Botaurus stellaris,"Tammsaare, Tartu City, Tartu maakond",XC931577-BOTSTE_NFC_240903_kl0031_Tammsaare_TT...,https://xeno-canto.org/sounds/uploaded/VTBSPKD...,58.3836,26.6918,Eurasian Bittern
3,3886143518,10 s,CC_BY_NC_4_0,Frank Lambert,NaN,NaN,flight call,Animalia,Chordata,Aves,...,2021-12-07,07:54,animal seen:yes; playback used:no,Egretta gularis,"Nahud, Al Birk mangroves, Aseer Province",XC741260-Western%20Reef%20Egret-FL%20flight%20...,https://xeno-canto.org/sounds/uploaded/YTUXOCT...,18.2893,41.4817,Western Reef Heron
4,4538106500,174 s,CC_BY_NC_4_0,Marc Anderson,Indeterminate,NaN,song,Animalia,Chordata,Aves,...,2023-09-08,07:00,animal seen:no; playback used:no,Numida meleagris,Northern Tuli Game Reserve,XC878083-Guineafowl_Helmeted2_M6EW-1015_Tuli_M...,https://xeno-canto.org/sounds/uploaded/EHGWCIG...,-22.2289,28.9551,Helmeted Guineafowl
5,2243593727,86 s,CC_BY_NC_4_0,Frank Lambert,NaN,NaN,call,Animalia,Chordata,Aves,...,2012-11-14,05:50,This species is not supposed to occur on Lombo...,Pomatorhinus montanus,"Gunung Rinjani, above Senaru, Lombok, West Nus...",XC166736-Pomatorhinus_montanus-FL%20calls%20Ab...,https://xeno-canto.org/sounds/uploaded/YTUXOCT...,-8.3235,116.4012,Javan Scimitar Babbler
6,2432431301,124 s,CC_BY_NC_4_0,david m,NaN,NaN,"call, flight call",Animalia,Chordata,Aves,...,1995-05-04,NaN,Bar-headed goose call ... not filtered ... par...,Anser indicus,"Houghton Regis, Central Bedfordshire, England",XC499742-190925_3354.mp3,https://xeno-canto.org/sounds/uploaded/BTOFEKX...,51.9009,-0.5386,Bar-headed Goose
7,2243642358,15 s,CC_BY_NC_4_0,Peter Boesman,NaN,NaN,call,Animalia,Chordata,Aves,...,2007-02-16,17:15,ID certainty 100%. (Archiv. tape 500 side A tr...,Dryobates scalaris,"Madera Canyon area, AZ",XC227962-Ladder-backed%20Woodpecker%20C%204574...,https://xeno-canto.org/sounds/uploaded/OOECIWC...,31.7287,-110.8758,Ladder-backed Woodpecker
8,4173218293,39 s,CC_BY_NC_4_0,Brendan Sloan,Male,NaN,call,Animalia,Chordata,Aves,...,2023-04-05,08:00,animal seen:yes; playback used:no,Phoeniculus bollei,Castle Lodge Mount Kenya,XC817087-0748-White-headed-wood-hoopoe.mp3,https://xeno-canto.org/sounds/uploaded/TNTQAOF...,NaN,NaN,White-headed Wood Hoopoe
9,5151719792,7 s,CC_BY_NC_4_0,Teus Luijendijk,NaN,NaN,call,Animalia,Chordata,Aves,...,2025-03-23,08:13,One call of a generally silent bird. Mild lowp...,Phylloscopus proregulus,"'s-Gravendeel, Hoeksche Waard, Zuid-Holland",XC982313-202503230813-Pallas-Boszanger_0933.mp3,https://xeno-canto.org/sounds/uploaded/VLNULZJ...,51.7918,4.6173,Pallas's Leaf Warbler

In [149]:
new_xc_data_v2.to_csv("gs://xeno-canto/dump_2025/xeno_canto_metadata.csv", index=False)