In [1]:
import pandas as pd

In [53]:
traindf = pd.read_csv("/home/gagan/open_audio_datasets/macaques/annotations.csv")

In [54]:
traindf.shape

(7285, 3)

In [56]:
traindf.head(10)

  class  split    filename
0    TH  train    TH28.wav
1    TH  train    TH22.wav
2    TH  train   TH928.wav
3    TH  train  TH1145.wav
4    TH  valid   TH470.wav
5    TH  train   TH372.wav
6    TH  train   TH941.wav
7    TH  train   TH920.wav
8    TH  valid   TH791.wav
9    TH  valid   TH565.wav

In [57]:
traindf["class"].unique()

array(['TH', 'BE', 'AL', 'MU', 'QU', 'SN', 'IO', 'TW'], dtype=object)

# Make separate splits

In [58]:
valdf = traindf[traindf["split"] == "valid"]
valdf.shape

(1457, 3)

In [59]:
traindf = traindf[traindf["split"] == "train"]
traindf.shape

(5828, 3)

# Add sex identity column

In [60]:
sex_mapping = {
    "TH": "female",
    "TW": "female",
    "SN": "female",
    "IO": "female",
    "MU": "male",
    "QU": "male",
    "BE": "male",
    "AL": "male"
}

In [61]:
traindf["sex"] = traindf["class"].apply(lambda x: sex_mapping[x])
valdf["sex"] = valdf["class"].apply(lambda x: sex_mapping[x])

In [62]:
traindf.shape

(5828, 4)

# Drop split column

In [63]:
traindf.drop("split", axis=1, inplace=True)
valdf.drop("split", axis=1, inplace=True)

# Rename 'filename' to 'file_name'

In [64]:
traindf.rename(columns={"filename": "file_name"}, inplace=True)
valdf.rename(columns={"filename": "file_name"}, inplace=True)

In [65]:
traindf.columns

Index(['class', 'file_name', 'sex'], dtype='object')

# Add local_path

In [66]:
traindf["local_path"] = traindf["file_name"].apply(lambda x: "audio/" + x)
valdf["local_path"] = valdf["file_name"].apply(lambda x: "audio/" + x)

# Rename 'class' to individual_id so that it doesn't clash with taxonomy columns

In [67]:
traindf.rename(columns={"class": "individual_id"}, inplace=True)
valdf.rename(columns={"class": "individual_id"}, inplace=True)

In [68]:
traindf.columns

Index(['individual_id', 'file_name', 'sex', 'local_path'], dtype='object')

# Add taxonomy

In [69]:
species_scientific = "Macaca mulatta"
species_common = "Rhesus macaque"
kindom = "Animalia"
phylum = "Chordata"
class_ = "Mammalia"
order = "Primates"
family = "Cercopithecidae"
genus = "Macaca"
taxonomic_name = "Chordata Mammalia Primates Cercopithecidae Macaca mulatta"

In [71]:
L = len(traindf)
traindf_tax = {"gbifID": [2436604] * L,
               "species_scientific": [species_scientific] * L,
               "species_common": [species_common] * L,
               "kingdom": [kindom] * L,
               "phylum": [phylum] * L,
               "class": [class_] * L,
               "order": [order] * L,
               "family": [family] * L,
               "genus": [genus] * L,
               "taxonomic_name": [taxonomic_name] * L,
              }
traindf_tax = pd.DataFrame(traindf_tax)

In [73]:
traindf_tax.shape

(5828, 10)

In [72]:
L = len(valdf)
valdf_tax = {"gbifID": [2436604] * L,
               "species_scientific": [species_scientific] * L,
               "species_common": [species_common] * L,
               "kingdom": [kindom] * L,
               "phylum": [phylum] * L,
               "class": [class_] * L,
               "order": [order] * L,
               "family": [family] * L,
               "genus": [genus] * L,
               "taxonomic_name": [taxonomic_name] * L,
              }
valdf_tax = pd.DataFrame(valdf_tax)

## concatenate

In [74]:
train_df = pd.concat([traindf.reset_index(drop=True), traindf_tax], axis=1)

In [76]:
train_df.shape

(5828, 14)

In [78]:
train_df.head(5)

,individual_id,file_name,sex,local_path,gbifID,species_scientific,species_common,kingdom,phylum,class,order,family,genus,taxonomic_name
0,TH,TH28.wav,female,audio/TH28.wav,2436604,Macaca mulatta,Rhesus macaque,Animalia,Chordata,Mammalia,Primates,Cercopithecidae,Macaca,Chordata Mammalia Primates Cercopithecidae Mac...
1,TH,TH22.wav,female,audio/TH22.wav,2436604,Macaca mulatta,Rhesus macaque,Animalia,Chordata,Mammalia,Primates,Cercopithecidae,Macaca,Chordata Mammalia Primates Cercopithecidae Mac...
2,TH,TH928.wav,female,audio/TH928.wav,2436604,Macaca mulatta,Rhesus macaque,Animalia,Chordata,Mammalia,Primates,Cercopithecidae,Macaca,Chordata Mammalia Primates Cercopithecidae Mac...
3,TH,TH1145.wav,female,audio/TH1145.wav,2436604,Macaca mulatta,Rhesus macaque,Animalia,Chordata,Mammalia,Primates,Cercopithecidae,Macaca,Chordata Mammalia Primates Cercopithecidae Mac...
4,TH,TH372.wav,female,audio/TH372.wav,2436604,Macaca mulatta,Rhesus macaque,Animalia,Chordata,Mammalia,Primates,Cercopithecidae,Macaca,Chordata Mammalia Primates Cercopithecidae Mac...

In [80]:
val_df = pd.concat([valdf.reset_index(drop=True), valdf_tax], axis=1)
val_df.columns

Index(['individual_id', 'file_name', 'sex', 'local_path', 'gbifID',
       'species_scientific', 'species_common', 'kingdom', 'phylum', 'class',
       'order', 'family', 'genus', 'taxonomic_name'],
      dtype='object')

In [81]:
val_df.head(4)

,individual_id,file_name,sex,local_path,gbifID,species_scientific,species_common,kingdom,phylum,class,order,family,genus,taxonomic_name
0,TH,TH470.wav,female,audio/TH470.wav,2436604,Macaca mulatta,Rhesus macaque,Animalia,Chordata,Mammalia,Primates,Cercopithecidae,Macaca,Chordata Mammalia Primates Cercopithecidae Mac...
1,TH,TH791.wav,female,audio/TH791.wav,2436604,Macaca mulatta,Rhesus macaque,Animalia,Chordata,Mammalia,Primates,Cercopithecidae,Macaca,Chordata Mammalia Primates Cercopithecidae Mac...
2,TH,TH565.wav,female,audio/TH565.wav,2436604,Macaca mulatta,Rhesus macaque,Animalia,Chordata,Mammalia,Primates,Cercopithecidae,Macaca,Chordata Mammalia Primates Cercopithecidae Mac...
3,TH,TH1285.wav,female,audio/TH1285.wav,2436604,Macaca mulatta,Rhesus macaque,Animalia,Chordata,Mammalia,Primates,Cercopithecidae,Macaca,Chordata Mammalia Primates Cercopithecidae Mac...

In [82]:
val_df.shape

(1457, 14)

# Save

In [83]:
train_df.to_csv("/home/gagan/open_audio_datasets/macaques/train.csv", index=False)
val_df.to_csv("//home/gagan/open_audio_datasets/macaques/val.csv", index=False)