In [1]:
import os
import numpy as np
from pathlib import Path
import pandas as pd

In [2]:
df47 = pd.read_csv("/home/gagan/open_audio_datasets/insectset_47_66/insectset_47_66_Insect47_Train_Val_Test_Annotation.csv")
df47.columns

Index(['file_name', 'species', 'subset', 'unique_file', 'link', 'contributor'], dtype='object')

In [5]:
df66 = pd.read_csv("/home/gagan/open_audio_datasets/insectset_47_66/insectset_47_66_InsectSet66_Train_Val_Test_Annotation.csv")
df66.columns

Index(['file_name', 'species', 'subset', 'unique_file', 'link', 'contributor'], dtype='object')

In [8]:
dfcomb1 = pd.concat([df47, df66], axis=0)
dfcomb1.head(5)

,file_name,species,subset,unique_file,link,contributor
0,Roeselianaroeselii_XC751814-dat028-019_edit1.wav,Roeselianaroeselii,train,Roeselianaroeselii_XC751814-dat028-019,https://xeno-canto.org/751814,Baudewijn Odé
1,Roeselianaroeselii_XC752367-dat006-010.wav,Roeselianaroeselii,validation,Roeselianaroeselii_XC752367-dat006-010,https://xeno-canto.org/752367,Baudewijn Odé
2,Gomphocerippusrufus_XC752285-dat001-045.wav,Gomphocerippusrufus,train,Gomphocerippusrufus_XC752285-dat001-045,https://xeno-canto.org/752285,Baudewijn Odé
3,Chorthippusalbomarginatus_XC751395-dat022-012_...,Chorthippusalbomarginatus,test,Chorthippusalbomarginatus_XC751395-dat022-012,https://xeno-canto.org/751395,Baudewijn Odé
4,Phaneropteranana_XC755717-221013-Phaneroptera-...,Phaneropteranana,test,Phaneropteranana_XC755717-221013-Phaneroptera-...,https://xeno-canto.org/755717,Frank Holzapfel

In [15]:
dfcomb1.sample(n=10)

,file_name,species,subset,unique_file,link,contributor,file_name_wo_ext
2133,Barbitistesyersini_XC752503-dat053-003_edit2.wav,Barbitistesyersini,train,Barbitistesyersini_XC752503-dat053-003,https://xeno-canto.org/752503,Baudewijn Odé,Barbitistesyersini_XC752503-dat053-003_edit2
1874,Gampsocleisglabra_XC752358-dat026-002_edit1.wav,Gampsocleisglabra,train,Gampsocleisglabra_XC752358-dat026-002,https://xeno-canto.org/752358,Baudewijn Odé,Gampsocleisglabra_XC752358-dat026-002_edit1
364,Chorthippusapricarius_XC752127-dat035-001_edit...,Chorthippusapricarius,train,Chorthippusapricarius_XC752127-dat035-001,https://xeno-canto.org/752127,Baudewijn Odé,Chorthippusapricarius_XC752127-dat035-001_edit8
475,Yoyettarepetens_GBIF2563524533_IN37765694_5525...,Yoyettarepetens,train,Yoyettarepetens_GBIF2563524533_IN37765694_55251,https://www.inaturalist.org/observations/37765694,Christie,Yoyettarepetens_GBIF2563524533_IN37765694_55251
746,Roeselianaroeselii_XC752364-dat006-006.wav,Roeselianaroeselii,train,Roeselianaroeselii_XC752364-dat006-006,https://xeno-canto.org/752364,Baudewijn Odé,Roeselianaroeselii_XC752364-dat006-006
576,Oecanthuspellucens_GBIF3903006649_IN131502279_...,Oecanthuspellucens,train,Oecanthuspellucens_GBIF3903006649_IN131502279_...,https://www.inaturalist.org/observations/13150...,Lennart Hudel,Oecanthuspellucens_GBIF3903006649_IN131502279_...
2079,Gryllusbimaculatus_XC751733-dat001-027.wav,Gryllusbimaculatus,train,Gryllusbimaculatus_XC751733-dat001-027,https://xeno-canto.org/751733,Baudewijn Odé,Gryllusbimaculatus_XC751733-dat001-027
1222,Yoyettacelis_GBIF3398771899_IN97410930_318525.wav,Yoyettacelis,train,Yoyettacelis_GBIF3398771899_IN97410930_318525,https://www.inaturalist.org/observations/97410930,Christie,Yoyettacelis_GBIF3398771899_IN97410930_318525
974,Chorthippusapricarius_XC752594-dat004-029.wav,Chorthippusapricarius,train,Chorthippusapricarius_XC752594-dat004-029,https://xeno-canto.org/752594,Baudewijn Odé,Chorthippusapricarius_XC752594-dat004-029
628,Pseudochorthippusmontanus_XC752606-dat012-004_...,Pseudochorthippusmontanus,validation,Pseudochorthippusmontanus_XC752606-dat012-004,https://xeno-canto.org/752606,Baudewijn Odé,Pseudochorthippusmontanus_XC752606-dat012-004_...

In [9]:
dfcomb1.shape

(5153, 6)

In [10]:
dfcomb1 = dfcomb1.drop_duplicates()
dfcomb1.shape

(3183, 6)

In [ ]:
dfc

In [6]:
df459 = pd.read_csv("/home/gagan/open_audio_datasets/insectset_47_66/InsectSet459_Train_Val_Annotation.csv")

In [7]:
df459.columns

Index(['file_name', 'species_name', 'group', 'license', 'contributor',
       'observation', 'file', 'background', 'original_name', 'subset'],
      dtype='object')

In [11]:
df459.shape

(21180, 10)

In [13]:
df459.head(5)

,file_name,species_name,group,license,contributor,observation,file,background,original_name,subset
0,Eunemobius_carolinus_IN435132_563.mp3,Eunemobius_carolinus,Orthoptera,http://creativecommons.org/publicdomain/zero/1.0/,Kent McFarland,https://www.inaturalist.org/observations/435132,https://static.inaturalist.org/sounds/563.mp3?...,NaN,Eunemobius_carolinus,Train
1,Tettigonia_viridissima_IN229082203_1131087.mp3,Tettigonia_viridissima,Orthoptera,http://creativecommons.org/publicdomain/zero/1.0/,ahabo,https://www.inaturalist.org/observations/22908...,https://static.inaturalist.org/sounds/1131087....,NaN,Tettigonia_viridissima,Train
2,Oecanthus_dulcisonans_IN232353068_1146352.mp3,Oecanthus_dulcisonans,Orthoptera,http://creativecommons.org/licenses/by-nc/4.0/,mathieu_pelissie,https://www.inaturalist.org/observations/23235...,https://static.inaturalist.org/sounds/1146352....,NaN,Oecanthus_dulcisonans,Validation
3,Eumodicogryllus_bordigalensis_IN231583058_1142...,Eumodicogryllus_bordigalensis,Orthoptera,http://creativecommons.org/licenses/by-nc/4.0/,Tomáš Dvořák,https://www.inaturalist.org/observations/23158...,https://static.inaturalist.org/sounds/1142992....,NaN,Eumodicogryllus_bordigalensis,Validation
4,Oecanthus_pellucens_IN231470435_1142536.mp3,Oecanthus_pellucens,Orthoptera,http://creativecommons.org/licenses/by-nc/4.0/,brigospo,https://www.inaturalist.org/observations/23147...,https://static.inaturalist.org/sounds/1142536....,NaN,Oecanthus_pellucens,Validation

In [16]:
df459["file_name_wo_ext"] = df459["file_name"].apply(lambda x: Path(x).stem)

In [14]:
dfcomb1["file_name_wo_ext"] = dfcomb1["file_name"].apply(lambda x: Path(x).stem)
dfcomb1["file_name_wo_ext"].head(3)

0    Roeselianaroeselii_XC751814-dat028-019_edit1
1          Roeselianaroeselii_XC752367-dat006-010
2         Gomphocerippusrufus_XC752285-dat001-045
Name: file_name_wo_ext, dtype: object

In [12]:
dfcomb1["file_name"].isin(df459["file_name"]).sum()

np.int64(0)

In [18]:
dfcomb1["file_name_wo_ext"].isin(df459["file_name_wo_ext"]).sum()

np.int64(0)

# Fix species names in dfcomb1 ?

In [22]:
!uv pip install duckdb

Using Python 3.10.16 environment at: /home/gagan/esp_projects/esp-data/.venv
Resolved 1 package in 171ms
Prepared 1 package in 259ms
Installed 1 package in 5ms
 + duckdb==1.3.0

In [23]:
import duckdb

In [28]:
conn = duckdb.connect("/home/gagan/esp_projects/taxonomy/app/gbif_taxonomy.db")

In [25]:
res = conn.execute("""SELECT ScientificName FROM gbif""").fetch_df()

In [27]:
#conn.close()

In [75]:
def get_taxonomy(sci_name: str):
    query = f"""SELECT TaxonID as gbifID, Kingdom as kingdom, Phylum as phylum, "Class" as class, "Order" as order, Family as family,
    Genus as genus, CommonNames as species_common
    FROM gbif WHERE ScientificName='{sci_name}'
    """
    res = conn.execute(query).fetch_df()
    if res.empty():
        return None
    res = res.iloc[0]
    return res.to_dict()

In [37]:
get_taxonomy("Eunemobius carolinus")

{'gbifID': 1721575,
 'kingdom': 'Animalia',
 'phylum': 'Arthropoda',
 'class': 'Insecta',
 'order': 'Orthoptera',
 'family': 'Trigonidiidae',
 'genus': 'Eunemobius',
 'species_common': 'carolina ground cricket'}

In [26]:
res.shape

(4961031, 1)

In [40]:
res.head(3)

                ScientificName
0  Veronicastrum lungtsuanense
1             Erigone cristata
2      Thysananthus amazonicus

In [42]:
res_mut = {"".join(r.split(" ")): r for r in res["ScientificName"].tolist()}

In [44]:
list(res_mut.keys())[:5]

['Veronicastrumlungtsuanense',
 'Erigonecristata',
 'Thysananthusamazonicus',
 'Ahomanachilensis',
 'Costatoverrucabaxteri']

In [45]:
list(res_mut.values())[:5]

['Veronicastrum lungtsuanense',
 'Erigone cristata',
 'Thysananthus amazonicus',
 'Ahomana chilensis',
 'Costatoverruca baxteri']

In [49]:
res_mut["Omocestusviridulus"] = "Omocestus viridulus"

In [52]:
res_mut['Omocestuspetraeus'] = "Omocestus petraeus"

# First fix the insect set 47 and 66

Problem with this approach is that the gbif taxonomy doesn't have a lot of entries

In [ ]:
dfcomb1["species_scientific"] = dfcomb1["species"].apply(lambda x: res_mut[x])

# Just use insectset_459 ?

In [54]:
df459["background"].notnull().sum()

np.int64(586)

In [55]:
df459.shape

(21180, 11)

## Split into train and val

In [125]:
train_df = df459[df459["subset"] == "Train"]
train_df.shape

(15873, 11)

In [126]:
val_df = df459[df459["subset"] == "Validation"]
val_df.shape

(5307, 11)

## Drop unnecessary columns

In [127]:
train_df = train_df.drop(labels=["subset", "original_name", "file_name_wo_ext"], axis=1)
train_df.head(4)

,file_name,species_name,group,license,contributor,observation,file,background
0,Eunemobius_carolinus_IN435132_563.mp3,Eunemobius_carolinus,Orthoptera,http://creativecommons.org/publicdomain/zero/1.0/,Kent McFarland,https://www.inaturalist.org/observations/435132,https://static.inaturalist.org/sounds/563.mp3?...,NaN
1,Tettigonia_viridissima_IN229082203_1131087.mp3,Tettigonia_viridissima,Orthoptera,http://creativecommons.org/publicdomain/zero/1.0/,ahabo,https://www.inaturalist.org/observations/22908...,https://static.inaturalist.org/sounds/1131087....,NaN
5,Hapithus_saltator_IN232354398_139533.wav,Hapithus_saltator,Orthoptera,http://creativecommons.org/licenses/by-nc/4.0/,jmole,https://www.inaturalist.org/observations/23235...,https://static.inaturalist.org/sounds/139533.w...,NaN
6,Pterophylla_camellifolia_IN227672804_1123507.mp3,Pterophylla_camellifolia,Orthoptera,http://creativecommons.org/licenses/by-nc/4.0/,jabaise94,https://www.inaturalist.org/observations/22767...,https://static.inaturalist.org/sounds/1123507....,NaN

In [128]:
val_df = val_df.drop(labels=["subset", "original_name", "file_name_wo_ext"], axis=1)
val_df.head(4)

,file_name,species_name,group,license,contributor,observation,file,background
2,Oecanthus_dulcisonans_IN232353068_1146352.mp3,Oecanthus_dulcisonans,Orthoptera,http://creativecommons.org/licenses/by-nc/4.0/,mathieu_pelissie,https://www.inaturalist.org/observations/23235...,https://static.inaturalist.org/sounds/1146352....,NaN
3,Eumodicogryllus_bordigalensis_IN231583058_1142...,Eumodicogryllus_bordigalensis,Orthoptera,http://creativecommons.org/licenses/by-nc/4.0/,Tomáš Dvořák,https://www.inaturalist.org/observations/23158...,https://static.inaturalist.org/sounds/1142992....,NaN
4,Oecanthus_pellucens_IN231470435_1142536.mp3,Oecanthus_pellucens,Orthoptera,http://creativecommons.org/licenses/by-nc/4.0/,brigospo,https://www.inaturalist.org/observations/23147...,https://static.inaturalist.org/sounds/1142536....,NaN
24,Neocurtilla_hexadactyla_IN213525028_1017835.mp3,Neocurtilla_hexadactyla,Orthoptera,http://creativecommons.org/licenses/by-nc/4.0/,Mark Nolen,https://www.inaturalist.org/observations/21352...,https://static.inaturalist.org/sounds/1017835....,NaN

### Optional: Apply _to_list?

In [64]:
def _to_list(v: str | float) -> list[str]:
    if pd.isna(v):
        return []
    elif isinstance(v, str):
        return [item.strip() for item in v.split(",")]
    else:
        raise ValueError(
            f"Expected a string or NaN, but got {v} of type {type(v)}"
        )

## Rename species column
and get rid of the "_" in the name

In [129]:
train_df["species_scientific"] = train_df["species_name"].apply(lambda x: x.replace("_", " "))
train_df = train_df.drop(["species_name"], axis=1)
train_df.columns

Index(['file_name', 'group', 'license', 'contributor', 'observation', 'file',
       'background', 'species_scientific'],
      dtype='object')

In [130]:
val_df["species_scientific"] = val_df["species_name"].apply(lambda x: x.replace("_", " "))
val_df = val_df.drop(["species_name"], axis=1)
val_df.columns

Index(['file_name', 'group', 'license', 'contributor', 'observation', 'file',
       'background', 'species_scientific'],
      dtype='object')

In [131]:
val_df.shape

(5307, 8)

## Add taxonomy

In [ ]:
!uv pip install pygbif

In [77]:
from pygbif import species as species

In [91]:
import time

In [104]:
def get_taxonomy_and_update(sci_name: str) -> dict:
    """
    Get GBIF taxonomy data for a given scientific name and update the database if necessary.
    """
    # Use parameterized query
    query = """SELECT TaxonID as gbifID, Kingdom as kingdom, Phylum as phylum, 
               "Class" as class, "Order" as order, Family as family,
               Genus as genus, CommonNames as species_common
               FROM gbif WHERE ScientificName = ?"""
    
    print(f"Checking database for: {sci_name}")
    res = conn.execute(query, [sci_name]).fetch_df()
    print(f"Query result shape: {res.shape}")
    
    if res.empty:
        print(f"Looking for {sci_name} in gbif API") 
        data = species.name_backbone(sci_name)
        time.sleep(1.5)
        
        if data and data["status"] == "ACCEPTED":
            print(f"Found it!, updating db")
            if data.get("usageKey"):
                try:
                    # Use parameterized insert
                    update_query = """INSERT INTO gbif (TaxonID, ScientificName, Kingdom, Phylum, "Class", "Order", Family, Genus, CommonNames)
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)"""
                    
                    conn.execute(update_query, [
                        data["usageKey"],
                        data.get("scientificName", sci_name),
                        data.get("kingdom", ""),
                        data.get("phylum", ""),
                        data.get("class", ""),
                        data.get("order", ""),
                        data.get("family", ""),
                        data.get("genus", ""),
                        data.get("commonName", [""])[0] if data.get("commonName") else ""
                    ])
                    conn.commit()
                    
                    # Verify the insert worked
                    verify_res = conn.execute(query, [sci_name]).fetch_df()
                    print(f"After insert, query result shape: {verify_res.shape}")
                    
                except Exception as e:
                    print(f"Error inserting data: {e}")

                return {
                    "gbifID": data["usageKey"],
                    "kingdom": data.get("kingdom", ""),
                    "phylum": data.get("phylum", ""),
                    "class": data.get("class", ""),
                    "order": data.get("order", ""),
                    "family": data.get("family", ""),
                    "genus": data.get("genus", ""),
                    "species_common": data.get("commonName", [""])[0] if data.get("commonName") else "",
                }
        
        # Return empty result if not found
        return {
            "gbifID": None,
            "kingdom": "",
            "phylum": "",
            "class": "",
            "order": "",
            "family": "",
            "genus": "",
            "species_common": "",
        }
    else:
        print(f"Found in database!")
        return res.iloc[0].to_dict()

In [103]:
all_train_species = train_df["species_scientific"].unique().tolist()
len(all_train_species)

459

In [ ]:
train_taxonomy = {}

for s in all_train_species:
    tax = get_taxonomy_and_update(s)
    train_taxonomy[s] = tax

In [106]:
# verify everything there
for k, v in train_taxonomy.items():
    if not v["gbifID"]:
        break

In [108]:
train_taxonomy["Omocestus viridulus"]

{'gbifID': 1710755,
 'kingdom': 'Animalia',
 'phylum': 'Arthropoda',
 'class': 'Insecta',
 'order': 'Orthoptera',
 'family': 'Acrididae',
 'genus': 'Omocestus',
 'species_common': ''}

### Issues with updating the db

In [111]:
update_query = """INSERT INTO gbif (TaxonID, ScientificName, Kingdom, Phylum, "Class", "Order", Family, Genus, CommonNames)
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)"""

d = train_taxonomy["Omocestus viridulus"]
conn.execute(update_query, [
    d["gbifID"],
    d.get("scientificName", "Omocestus viridulus"),
    d.get("kingdom", ""),
    d.get("phylum", ""),
    d.get("class", ""),
    d.get("order", ""),
    d.get("family", ""),
    d.get("genus", ""),
    d.get("species_common", [""])[0] if d.get("species_common") else ""
])
conn.commit()

In [112]:
query = f"""SELECT TaxonID as gbifID, Kingdom as kingdom, Phylum as phylum, "Class" as class, "Order" as order, Family as family,
    Genus as genus, CommonNames as species_common
    FROM gbif WHERE ScientificName='{"Omocestus rufipes"}'
    """
conn.execute(query).fetch_df()

Empty DataFrame
Columns: [gbifID, kingdom, phylum, class, order, family, genus, species_common]
Index: []

## Update train_df and val_df taxonomy

In [132]:
train_df_taxonomy = []
for s in train_df["species_scientific"].tolist():
    train_df_taxonomy.append(train_taxonomy[s])

In [133]:
val_df_taxonomy = []
for s in val_df["species_scientific"].tolist():
    val_df_taxonomy.append(train_taxonomy[s])

In [134]:
train_df_taxonomy = pd.DataFrame(train_df_taxonomy)

In [135]:
train_df_taxonomy.head(3)

,gbifID,kingdom,phylum,class,order,family,genus,species_common
0,1721575,Animalia,Arthropoda,Insecta,Orthoptera,Trigonidiidae,Eunemobius,carolina ground cricket
1,1692898,Animalia,Arthropoda,Insecta,Orthoptera,Tettigoniidae,Tettigonia,"great green bush cricket, great green bush-cri..."
2,9480592,Animalia,Arthropoda,Insecta,Orthoptera,Gryllidae,Hapithus,jumping bush cricket

In [136]:
train_df_taxonomy.species_common.isnull().sum()

np.int64(7651)

In [137]:
val_df_taxonomy = pd.DataFrame(val_df_taxonomy)
val_df_taxonomy.head(3)

,gbifID,kingdom,phylum,class,order,family,genus,species_common
0,1721001,Animalia,Arthropoda,Insecta,Orthoptera,Gryllidae,Oecanthus,None
1,1722140,Animalia,Arthropoda,Insecta,Orthoptera,Gryllidae,Eumodicogryllus,"bordeaux cricket, verge cricket"
2,1720967,Animalia,Arthropoda,Insecta,Orthoptera,Gryllidae,Oecanthus,"tree cricket, tree-cricket"

In [138]:
train_df_taxonomy.shape

(15873, 8)

In [139]:
val_df_taxonomy.shape

(5307, 8)

## Merge taxonomy with original
and drop the 'group'

In [155]:
train_df.reset_index(inplace=True, drop=True)
train_df_taxonomy.reset_index(inplace=True, drop=True)

In [164]:
train_df2 = pd.concat([train_df, train_df_taxonomy], axis=1, ignore_index=False).drop(labels="index", axis=1)

In [165]:
train_df2.shape

(15873, 16)

In [166]:
train_df2.head(3)

,file_name,group,license,contributor,observation,file,background,species_scientific,gbifID,kingdom,phylum,class,order,family,genus,species_common
0,Eunemobius_carolinus_IN435132_563.mp3,Orthoptera,http://creativecommons.org/publicdomain/zero/1.0/,Kent McFarland,https://www.inaturalist.org/observations/435132,https://static.inaturalist.org/sounds/563.mp3?...,NaN,Eunemobius carolinus,1721575,Animalia,Arthropoda,Insecta,Orthoptera,Trigonidiidae,Eunemobius,carolina ground cricket
1,Tettigonia_viridissima_IN229082203_1131087.mp3,Orthoptera,http://creativecommons.org/publicdomain/zero/1.0/,ahabo,https://www.inaturalist.org/observations/22908...,https://static.inaturalist.org/sounds/1131087....,NaN,Tettigonia viridissima,1692898,Animalia,Arthropoda,Insecta,Orthoptera,Tettigoniidae,Tettigonia,"great green bush cricket, great green bush-cri..."
2,Hapithus_saltator_IN232354398_139533.wav,Orthoptera,http://creativecommons.org/licenses/by-nc/4.0/,jmole,https://www.inaturalist.org/observations/23235...,https://static.inaturalist.org/sounds/139533.w...,NaN,Hapithus saltator,9480592,Animalia,Arthropoda,Insecta,Orthoptera,Gryllidae,Hapithus,jumping bush cricket

In [168]:
val_df.reset_index(inplace=True, drop=True)
val_df2 = pd.concat([val_df, val_df_taxonomy], axis=1, ignore_index=False)#.drop(labels="index", axis=1)

In [169]:

val_df2.shape

(5307, 16)

In [170]:
val_df2.head(3)

,file_name,group,license,contributor,observation,file,background,species_scientific,gbifID,kingdom,phylum,class,order,family,genus,species_common
0,Oecanthus_dulcisonans_IN232353068_1146352.mp3,Orthoptera,http://creativecommons.org/licenses/by-nc/4.0/,mathieu_pelissie,https://www.inaturalist.org/observations/23235...,https://static.inaturalist.org/sounds/1146352....,NaN,Oecanthus dulcisonans,1721001,Animalia,Arthropoda,Insecta,Orthoptera,Gryllidae,Oecanthus,None
1,Eumodicogryllus_bordigalensis_IN231583058_1142...,Orthoptera,http://creativecommons.org/licenses/by-nc/4.0/,Tomáš Dvořák,https://www.inaturalist.org/observations/23158...,https://static.inaturalist.org/sounds/1142992....,NaN,Eumodicogryllus bordigalensis,1722140,Animalia,Arthropoda,Insecta,Orthoptera,Gryllidae,Eumodicogryllus,"bordeaux cricket, verge cricket"
2,Oecanthus_pellucens_IN231470435_1142536.mp3,Orthoptera,http://creativecommons.org/licenses/by-nc/4.0/,brigospo,https://www.inaturalist.org/observations/23147...,https://static.inaturalist.org/sounds/1142536....,NaN,Oecanthus pellucens,1720967,Animalia,Arthropoda,Insecta,Orthoptera,Gryllidae,Oecanthus,"tree cricket, tree-cricket"

In [171]:
train_df2 = train_df2.drop("group", axis=1)
val_df2 = val_df2.drop("group", axis=1)

## Add the path column

In [178]:
train_df2["local_path"] = train_df2["file_name"].apply(lambda x: "audio/Train/" + x)
val_df2["local_path"] = val_df2["file_name"].apply(lambda x: "audio/Validation/" + x)

In [179]:
train_df2.head(3)

,file_name,license,contributor,observation,file,background,species_scientific,gbifID,kingdom,phylum,class,order,family,genus,species_common,local_path
0,Eunemobius_carolinus_IN435132_563.mp3,http://creativecommons.org/publicdomain/zero/1.0/,Kent McFarland,https://www.inaturalist.org/observations/435132,https://static.inaturalist.org/sounds/563.mp3?...,NaN,Eunemobius carolinus,1721575,Animalia,Arthropoda,Insecta,Orthoptera,Trigonidiidae,Eunemobius,carolina ground cricket,audio/Train/Eunemobius_carolinus_IN435132_563.mp3
1,Tettigonia_viridissima_IN229082203_1131087.mp3,http://creativecommons.org/publicdomain/zero/1.0/,ahabo,https://www.inaturalist.org/observations/22908...,https://static.inaturalist.org/sounds/1131087....,NaN,Tettigonia viridissima,1692898,Animalia,Arthropoda,Insecta,Orthoptera,Tettigoniidae,Tettigonia,"great green bush cricket, great green bush-cri...",audio/Train/Tettigonia_viridissima_IN229082203...
2,Hapithus_saltator_IN232354398_139533.wav,http://creativecommons.org/licenses/by-nc/4.0/,jmole,https://www.inaturalist.org/observations/23235...,https://static.inaturalist.org/sounds/139533.w...,NaN,Hapithus saltator,9480592,Animalia,Arthropoda,Insecta,Orthoptera,Gryllidae,Hapithus,jumping bush cricket,audio/Train/Hapithus_saltator_IN232354398_1395...

## Add taxonomic_name

In [204]:
train_taxonomic_name = [f"{r['phylum']} {r['class']} {r['order']} {r['family']} {r['species_scientific']}" for i, r in train_df2.iterrows()]
val_taxonomic_name = [f"{r['phylum']} {r['class']} {r['order']} {r['family']} {r['species_scientific']}" for i, r in val_df2.iterrows()]

In [205]:
train_taxonomic_name[:5]

['Arthropoda Insecta Orthoptera Trigonidiidae Eunemobius carolinus',
 'Arthropoda Insecta Orthoptera Tettigoniidae Tettigonia viridissima',
 'Arthropoda Insecta Orthoptera Gryllidae Hapithus saltator',
 'Arthropoda Insecta Orthoptera Tettigoniidae Pterophylla camellifolia',
 'Arthropoda Insecta Orthoptera Gryllidae Oecanthus rileyi']

In [206]:
train_df2["taxonomic_name"] = train_taxonomic_name
val_df2["taxonomic_name"] = val_taxonomic_name

## Save

In [208]:
train_df2.to_csv("/home/gagan/open_audio_datasets/insectset_459/insectset459_annotations_train.csv", index=False)

In [209]:
val_df2.to_csv("/home/gagan/open_audio_datasets/insectset_459/insectset459_annotations_val.csv", index=False)

In [184]:
import json

In [185]:
with open("/home/gagan/esp_projects/taxonomy/insects.json", "w") as f:
    json.dump(train_taxonomy, f)

# Try again to export missing annotations to gbif_taxonomy.db

In [194]:
conn = duckdb.connect("/home/gagan/esp_projects/taxonomy/app/gbif_taxonomy.db")

In [195]:
to_insert = {}
for k, v in train_taxonomy.items():
    
    # Check that the item exists in db
    query = f"""SELECT TaxonID as gbifID, Kingdom as kingdom, Phylum as phylum, "Class" as class, "Order" as order, Family as family,
    Genus as genus, CommonNames as species_common
    FROM gbif WHERE ScientificName='{k}'
    """
    res = conn.execute(query).fetch_df()

    if not res.empty:
        continue
    else:
        to_insert[k] = v

In [ ]:
to_insert

In [198]:
to_insert_df = []
for k, v in to_insert.items():
    to_insert_df.append((v["gbifID"], k, v["kingdom"], v["phylum"], v["class"], v["order"], v["family"], v["genus"], v["species_common"]))

# Insert batch
conn.executemany(
    """INSERT INTO gbif (TaxonID, ScientificName, Kingdom, Phylum, "Class", "Order", Family, Genus, CommonNames) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""", 
    to_insert_df
)
conn.commit()
conn.close()

## Verify with query

In [199]:
conn = duckdb.connect("/home/gagan/esp_projects/taxonomy/app/gbif_taxonomy.db")

In [200]:
query = f"""SELECT TaxonID as gbifID, Kingdom as kingdom, Phylum as phylum, "Class" as class, "Order" as order, Family as family,
    Genus as genus, CommonNames as species_common
    FROM gbif WHERE ScientificName='{"Omocestus rufipes"}'
    """
conn.execute(query).fetch_df()

,gbifID,kingdom,phylum,class,order,family,genus,species_common
0,1710802,Animalia,Arthropoda,Insecta,Orthoptera,Acrididae,Omocestus,

In [201]:
conn.close()