In [1]:
import pandas as pd

# Raw data

In [2]:
df = pd.read_csv("/home/gagan/open_audio_datasets/egyptian_fruit_bats/egyptian_fruit_bats_annotations.csv")

In [3]:
df.head(10)

   Emitter  File Name
0      216  69809.wav
1      215  71889.wav
2      216  46690.wav
3      230  85411.wav
4      215  45609.wav
5      216  90083.wav
6      215  42092.wav
7      216  44892.wav
8      216  26851.wav
9      230  58472.wav

In [6]:
df.shape

(10000, 2)

In [4]:
!gsutil -m cp "/home/gagan/open_audio_datasets/egyptian_fruit_bats/egyptian_fruit_bats_annotations.csv" "gs://esp-ml-datasets/egyptian_fruit_bats/v0.1.0/raw/"

Copying file:///home/gagan/open_audio_datasets/egyptian_fruit_bats/egyptian_fruit_bats_annotations.csv [Content-Type=text/csv]...
- [1/1 files][136.4 KiB/136.4 KiB] 100% Done
Operation completed over 1 objects/136.4 KiB.

# Copy raw data zip file to new location

In [5]:
!gsutil -m cp "gs://foundation-model-data/audio/egyptian_fruit_bats/egyptian_fruit_bats.zip" "gs://esp-ml-datasets/egyptian_fruit_bats/v0.1.0/raw/"

Copying gs://foundation-model-data/audio/egyptian_fruit_bats/egyptian_fruit_bats.zip [Content-Type=application/zip]...
/ [1/1 files][  4.9 GiB/  4.9 GiB] 100% Done     0.0 B/s
Operation completed over 1 objects/4.9 GiB.

## Beans processed data

In [7]:
traindf = pd.read_csv("gs://foundation-model-data/audio/egyptian_fruit_bats/annotations.train.csv", storage_options={"project": "okapi-274503"})
traindf.shape

(6000, 3)

In [8]:
traindf.head(5)

   Unnamed: 0                                      path  label
0           2  data/egyptian_fruit_bats/audio/46690.wav    216
1           4  data/egyptian_fruit_bats/audio/45609.wav    215
2           5  data/egyptian_fruit_bats/audio/90083.wav    216
3           6  data/egyptian_fruit_bats/audio/42092.wav    215
4           8  data/egyptian_fruit_bats/audio/26851.wav    216

# Taxonomy