# We are preparing gibbons dataset

Clink et al 2020 gibbons solo

In [20]:
import pandas as pd
import io
from pathlib import Path

In [5]:
selection_tables_path = "/home/gagan/open_audio_datasets/clink2020_gibbons/selection_tables/"
selection_tables = list(Path(selection_tables_path).glob("*selection*"))

In [6]:
selection_tables

[PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/selection_tables/M13_20190827_052003.Table.1.selections.txt'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/selection_tables/M9_20190823_044002.Table.1.selections.txt'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/selection_tables/S14_20180309_040001.Table.1.selections.txt'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/selection_tables/M10_20190824_052003.Table.1.selections.txt'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/selection_tables/M11_20190825_052003.Table.1.selections.txt'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/selection_tables/S11_20180307_060002.Table.1.selections.txt'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/selection_tables/S19_20180306_060002.Table.1.selections.txt'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/selection_tables/S11_20180307_040001.Table.1.selections.txt'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/selection_tables/S17_20180408_040001.Table.1.selections.txt'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/selection_tables/M11_20190825_044002.Table.1.selections.txt'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/selection_tables/S12_20180224_060002.Table.1.selections.txt'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/selection_tables/S20_20180308_060002.Table.1.selections.txt'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/selection_tables/S14_20180309_060002.Table.1.selections.txt'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/selection_tables/S10_20180701_040001.Table.1.selections.txt'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/selection_tables/S15_20180318_040002.Table.1.selections.txt'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/selection_tables/M10_20190824_044002.Table.1.selections.txt'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/selection_tables/S16_20180328_040002.Table.1.selections.txt'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/selection_tables/M9_20190823_052003.Table.1.selections.txt')]

In [18]:
table_names = [s.name.split(".Table")[0] for s in selection_tables]
table_names

['M13_20190827_052003',
 'M9_20190823_044002',
 'S14_20180309_040001',
 'M10_20190824_052003',
 'M11_20190825_052003',
 'S11_20180307_060002',
 'S19_20180306_060002',
 'S11_20180307_040001',
 'S17_20180408_040001',
 'M11_20190825_044002',
 'S12_20180224_060002',
 'S20_20180308_060002',
 'S14_20180309_060002',
 'S10_20180701_040001',
 'S15_20180318_040002',
 'M10_20190824_044002',
 'S16_20180328_040002',
 'M9_20190823_052003']

In [13]:
len(selection_tables)

18

In [7]:
wav_files_path = "/home/gagan/open_audio_datasets/clink2020_gibbons/wav/"

In [10]:
wav_files = list(Path(wav_files_path).glob("*wav"))

In [11]:
wav_files

[PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/wav/M9_20190823_052003.wav'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/wav/M11_20190825_044002.wav'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/wav/M10_20190824_052003.wav'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/wav/S14_20180309_060002.wav'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/wav/M11_20190825_052003.wav'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/wav/S11_20180307_060002.wav'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/wav/S17_20180408_040001.wav'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/wav/S15_20180318_040002.wav'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/wav/S11_20180307_040001.wav'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/wav/M10_20190824_044002.wav'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/wav/M9_20190823_044002.wav'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/wav/S14_20180309_040001.wav'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/wav/S12_20180224_060002.wav'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/wav/S19_20180308_060002.wav'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/wav/S19_20180306_060002.wav'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/wav/S20_20180308_060002.wav'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/wav/M13_20190827_052003.wav'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/wav/S16_20180328_040002.wav'),
 PosixPath('/home/gagan/open_audio_datasets/clink2020_gibbons/wav/S10_20180701_040001.wav')]

In [14]:
len(wav_files)

19

In [17]:
file_names = [w.stem for w in wav_files]
file_names

['M9_20190823_052003',
 'M11_20190825_044002',
 'M10_20190824_052003',
 'S14_20180309_060002',
 'M11_20190825_052003',
 'S11_20180307_060002',
 'S17_20180408_040001',
 'S15_20180318_040002',
 'S11_20180307_040001',
 'M10_20190824_044002',
 'M9_20190823_044002',
 'S14_20180309_040001',
 'S12_20180224_060002',
 'S19_20180308_060002',
 'S19_20180306_060002',
 'S20_20180308_060002',
 'M13_20190827_052003',
 'S16_20180328_040002',
 'S10_20180701_040001']

In [19]:
set(file_names).difference(table_names)

{'S19_20180308_060002'}

# Load a selection table to inspect

In [21]:
with open(selection_tables[0], "r") as f:
    st =  f.read()
st = pd.read_csv(io.StringIO(st), sep="\t")
st.head(3)

,Selection,View,Channel,Begin Time (s),End Time (s),Low Freq (Hz),High Freq (Hz),BW 90% (Hz),Dur 90% (s),Freq 5% (Hz),Freq 95% (Hz)
0,1,Spectrogram 1,1,1524.059647,1524.527507,576.687,828.221,109.375,0.384,656.250,765.625
1,2,Spectrogram 1,1,1524.701594,1524.875682,638.037,877.301,156.250,0.128,671.875,828.125
2,3,Spectrogram 1,1,1525.049769,1525.278259,631.902,889.571,156.250,0.192,703.125,859.375

In [23]:
st

,Selection,View,Channel,Begin Time (s),End Time (s),Low Freq (Hz),High Freq (Hz),BW 90% (Hz),Dur 90% (s),Freq 5% (Hz),Freq 95% (Hz)
0,1,Spectrogram 1,1,1524.059647,1524.527507,576.687,828.221,109.375,0.384,656.250,765.625
1,2,Spectrogram 1,1,1524.701594,1524.875682,638.037,877.301,156.250,0.128,671.875,828.125
2,3,Spectrogram 1,1,1525.049769,1525.278259,631.902,889.571,156.250,0.192,703.125,859.375
3,4,Spectrogram 1,1,1525.441466,1525.626434,668.712,1079.755,203.125,0.128,765.625,968.750
4,5,Spectrogram 1,1,1535.112503,1535.373634,754.601,1012.270,187.500,0.192,781.250,968.750
...,...,...,...,...,...,...,...,...,...,...,...
307,308,Spectrogram 1,1,2320.235582,2320.617403,633.032,845.114,62.500,0.288,687.500,750.000
308,309,Spectrogram 1,1,2320.749390,2321.230201,633.032,948.798,93.750,0.352,703.125,796.875
309,310,Spectrogram 1,1,2321.296195,2321.437610,689.587,1024.205,218.750,0.096,734.375,953.125
310,311,Spectrogram 1,1,2321.753437,2321.932563,736.717,1071.335,265.625,0.160,765.625,1031.250
311,312,Spectrogram 1,1,2322.220107,2322.370949,666.023,1104.325,250.000,0.128,781.250,1031.250

# Create file_name, local_path and selection_table dataframe

In [24]:
data = {
    "file_name": [t + ".wav" for t in table_names],
    "selection_table": [],
    "local_path": ["audio/" + s + ".wav" for s in table_names]
}

for s in selection_tables:
    with open(s, "r") as f:
        data["selection_table"].append(f.read())

In [25]:
data = pd.DataFrame(data)
data.head(3)

,file_name,selection_table,local_path
0,M13_20190827_052003.wav,Selection\tView\tChannel\tBegin Time (s)\tEnd ...,audio/M13_20190827_052003.wav
1,M9_20190823_044002.wav,Selection\tView\tChannel\tBegin Time (s)\tEnd ...,audio/M9_20190823_044002.wav
2,S14_20180309_040001.wav,Selection\tView\tChannel\tBegin Time (s)\tEnd ...,audio/S14_20180309_040001.wav

# Taxonomy

In [26]:
species_scientific = "Hylobates muelleri"
species_common = "Mueller's Gibbon"
kindom = "Animalia"
phylum = "Chordata"
class_ = "Mammalia"
order = "Primates"
family = "Hylobatidae"
genus = "Hylobates"
taxonomic_name = "Chordata Mammalia Primates Hylobatidae Hylobates mulleri"

In [28]:
L = len(data)
data = pd.concat([data, pd.DataFrame({
    "kingdom": [kindom] * L ,
    "phylum": [phylum] * L, 
    "class": [class_] * L,
    "order": [order] * L,
    "family": [family] * L,
    "genus": [genus] * L,
    "species_scientific": [species_scientific] * L,
    "species_common": [species_common] * L,
    "taxonomic_name": [taxonomic_name] * L,
})], axis=1)

In [29]:
data.head(5)

,file_name,selection_table,local_path,kingdom,phylum,class,order,family,genus,species_scientific,species_common,taxonomic_name
0,M13_20190827_052003.wav,Selection\tView\tChannel\tBegin Time (s)\tEnd ...,audio/M13_20190827_052003.wav,Animalia,Chordata,Mammalia,Primates,Hylobatidae,Hylobates,Hylobates muelleri,Mueller's Gibbon,Chordata Mammalia Primates Hylobatidae Hylobat...
1,M9_20190823_044002.wav,Selection\tView\tChannel\tBegin Time (s)\tEnd ...,audio/M9_20190823_044002.wav,Animalia,Chordata,Mammalia,Primates,Hylobatidae,Hylobates,Hylobates muelleri,Mueller's Gibbon,Chordata Mammalia Primates Hylobatidae Hylobat...
2,S14_20180309_040001.wav,Selection\tView\tChannel\tBegin Time (s)\tEnd ...,audio/S14_20180309_040001.wav,Animalia,Chordata,Mammalia,Primates,Hylobatidae,Hylobates,Hylobates muelleri,Mueller's Gibbon,Chordata Mammalia Primates Hylobatidae Hylobat...
3,M10_20190824_052003.wav,Selection\tView\tChannel\tBegin Time (s)\tEnd ...,audio/M10_20190824_052003.wav,Animalia,Chordata,Mammalia,Primates,Hylobatidae,Hylobates,Hylobates muelleri,Mueller's Gibbon,Chordata Mammalia Primates Hylobatidae Hylobat...
4,M11_20190825_052003.wav,Selection\tView\tChannel\tBegin Time (s)\tEnd ...,audio/M11_20190825_052003.wav,Animalia,Chordata,Mammalia,Primates,Hylobatidae,Hylobates,Hylobates muelleri,Mueller's Gibbon,Chordata Mammalia Primates Hylobatidae Hylobat...

In [30]:
data.to_csv("/home/gagan/open_audio_datasets/clink2020_gibbons/clink2020_gibbons_annotations.csv", index=False)