In [8]:
import pandas as pd
import io
import json

In [9]:
from esp_data.paths import AnyPath

In [3]:
import esp_data.file_io.functional as F

In [3]:
df = pd.read_csv("voxaboxen_data_humpback_formatted_test_info.csv")

In [4]:
df.shape

(129, 3)

In [5]:
df.columns

Index(['fn', 'audio_fp', 'selection_table_fp'], dtype='object')

In [6]:
df.head(3)

,fn,audio_fp,selection_table_fp
0,Hawaii_K_14_121216_190000___795,audio/Hawaii_K_14_121216_190000___795.wav,selection_tables/Hawaii_K_14_121216_190000___7...
1,Hawaii_K_14_121216_190000___56,audio/Hawaii_K_14_121216_190000___56.wav,selection_tables/Hawaii_K_14_121216_190000___5...
2,Hawaii_K_14_121216_190000___169,audio/Hawaii_K_14_121216_190000___169.wav,selection_tables/Hawaii_K_14_121216_190000___1...

In [8]:
df.selection_table_fp.iloc[0]

'selection_tables/Hawaii_K_14_121216_190000___795.txt'

In [13]:
path_to_humpback = AnyPath("gs://voxaboxen/voxaboxen_data/humpback/formatted")
path_to_humpback

GSPath('gs://voxaboxen/voxaboxen_data/humpback/formatted')

In [14]:
st_path = path_to_humpback / df.selection_table_fp.iloc[0]
st_path

GSPath('gs://voxaboxen/voxaboxen_data/humpback/formatted/selection_tables/Hawaii_K_14_121216_190000___795.txt')

In [26]:
data = F.read_text(st_path)
data

'Begin Time (s)\tEnd Time (s)\tAnnotation\tLow Freq (Hz)\tHigh Freq (Hz)\n25.294\t26.387\tMn\t100\t4900.0\n28.572\t29.489\tMn\t100\t4900.0\n30.652\t31.992\tMn\t100\t4900.0\n36.715\t37.948\tMn\t100\t4900.0\n42.178\t43.729\tMn\t100\t4900.0\n53.708\t55.012\tMn\t100\t4900.0\n57.797\t59.136\tMn\t100\t4900.0\n62.485\t63.507\tMn\t100\t4900.0\n67.807\t68.794\tMn\t100\t4900.0\n'

In [27]:
data = pd.read_csv(io.StringIO(data), sep='\t')

In [28]:
data

   Begin Time (s)  End Time (s) Annotation  Low Freq (Hz)  High Freq (Hz)
0          25.294        26.387         Mn            100          4900.0
1          28.572        29.489         Mn            100          4900.0
2          30.652        31.992         Mn            100          4900.0
3          36.715        37.948         Mn            100          4900.0
4          42.178        43.729         Mn            100          4900.0
5          53.708        55.012         Mn            100          4900.0
6          57.797        59.136         Mn            100          4900.0
7          62.485        63.507         Mn            100          4900.0
8          67.807        68.794         Mn            100          4900.0

In [47]:
dd = data.to_dict(orient="records")

In [48]:
dd

[{'Begin Time (s)': 25.294,
  'End Time (s)': 26.387,
  'Annotation': 'Mn',
  'Low Freq (Hz)': 100,
  'High Freq (Hz)': 4900.0},
 {'Begin Time (s)': 28.572,
  'End Time (s)': 29.489,
  'Annotation': 'Mn',
  'Low Freq (Hz)': 100,
  'High Freq (Hz)': 4900.0},
 {'Begin Time (s)': 30.652,
  'End Time (s)': 31.992,
  'Annotation': 'Mn',
  'Low Freq (Hz)': 100,
  'High Freq (Hz)': 4900.0},
 {'Begin Time (s)': 36.715,
  'End Time (s)': 37.948,
  'Annotation': 'Mn',
  'Low Freq (Hz)': 100,
  'High Freq (Hz)': 4900.0},
 {'Begin Time (s)': 42.178,
  'End Time (s)': 43.729,
  'Annotation': 'Mn',
  'Low Freq (Hz)': 100,
  'High Freq (Hz)': 4900.0},
 {'Begin Time (s)': 53.708,
  'End Time (s)': 55.012,
  'Annotation': 'Mn',
  'Low Freq (Hz)': 100,
  'High Freq (Hz)': 4900.0},
 {'Begin Time (s)': 57.797,
  'End Time (s)': 59.136,
  'Annotation': 'Mn',
  'Low Freq (Hz)': 100,
  'High Freq (Hz)': 4900.0},
 {'Begin Time (s)': 62.485,
  'End Time (s)': 63.507,
  'Annotation': 'Mn',
  'Low Freq (Hz)': 100,
  'High Freq (Hz)': 4900.0},
 {'Begin Time (s)': 67.807,
  'End Time (s)': 68.794,
  'Annotation': 'Mn',
  'Low Freq (Hz)': 100,
  'High Freq (Hz)': 4900.0}]

In [31]:
dff = pd.DataFrame(dd)
dff

   Begin Time (s)  End Time (s) Annotation  Low Freq (Hz)  High Freq (Hz)
0          25.294        26.387         Mn            100          4900.0
1          28.572        29.489         Mn            100          4900.0
2          30.652        31.992         Mn            100          4900.0
3          36.715        37.948         Mn            100          4900.0
4          42.178        43.729         Mn            100          4900.0
5          53.708        55.012         Mn            100          4900.0
6          57.797        59.136         Mn            100          4900.0
7          62.485        63.507         Mn            100          4900.0
8          67.807        68.794         Mn            100          4900.0

In [36]:
import torchaudio

In [43]:
with F.open_file(path_to_humpback / "audio/Hawaii_K_14_121216_190000___795.wav", "rb") as f:
    audio_data, sr = torchaudio.load(f)
    audio_data = audio_data.numpy().squeeze()

In [45]:
a = audio_data.tolist()
len(a)

750000

In [46]:
sr

10000

# Validate datasets already prepared

In [1]:
from datasets import load_dataset

/Users/gagan/esp_projects/esp-data/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
ds = load_dataset("parquet",data_files="gs://esp-ml-datasets/voxaboxen/processed/v1.0.0/parquet/humpback/test/*parquet",
                  split="train", name="humpback_test")

Downloading data: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 157M/157M [00:15<00:00, 10.1MB/s]
Generating train split: 129 examples [00:00, 280.01 examples/s]

In [4]:
ds

Dataset({
    features: ['source_dataset', 'metadata', 'id', 'audio', 'file_name', 'selection_table'],
    num_rows: 129
})

In [6]:
ds[0]["selection_table"]

'Begin Time (s)\tEnd Time (s)\tAnnotation\tLow Freq (Hz)\tHigh Freq (Hz)\n25.294\t26.387\tMn\t100\t4900.0\n28.572\t29.489\tMn\t100\t4900.0\n30.652\t31.992\tMn\t100\t4900.0\n36.715\t37.948\tMn\t100\t4900.0\n42.178\t43.729\tMn\t100\t4900.0\n53.708\t55.012\tMn\t100\t4900.0\n57.797\t59.136\tMn\t100\t4900.0\n62.485\t63.507\tMn\t100\t4900.0\n67.807\t68.794\tMn\t100\t4900.0'

In [15]:
ds[-1]["file_name"]

'Palmyra_WT_05_080802_024115___3'

In [7]:
len(ds[-1]["audio"])

750000

In [18]:
ds[-1]["metadata"]

'{"duration": 75.0, "sample_rate": 10000}'

In [11]:
hb_test_df = pd.read_csv("gs://voxaboxen/voxaboxen_data/humpback/formatted/test_info.csv",
                         storage_options={"project": "okapi-274503"})

In [12]:
hb_test_df.shape

(129, 3)

In [16]:
hb_test_df.iloc[-1]

fn                                      Palmyra_WT_05_080802_024115___3
audio_fp                      audio/Palmyra_WT_05_080802_024115___3.wav
selection_table_fp    selection_tables/Palmyra_WT_05_080802_024115__...
Name: 128, dtype: object

In [25]:
hawaii_test_df = pd.read_csv("gs://voxaboxen/voxaboxen_data/OZF/formatted/val_info.csv",
                         storage_options={"project": "okapi-274503"})

In [26]:
hawaii_test_df.shape

(6, 4)

In [27]:
hawaii_test_df.iloc[0].to_dict()

{'Unnamed: 0': 0,
 'fn': 'OZF46_val',
 'audio_fp': 'audio/OZF46_val.flac',
 'selection_table_fp': 'selection_tables/OZF46_val.txt'}